version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "toolkit/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "toolkit/build.gradle" }}
      - run:
          name: Build
          command: ./gradlew clean :toolkit:build
      - store_artifacts:
          path: toolkit/build/outputs
          destination: artifacts
      - store_artifacts:
          path: toolkit/build/reports
          destination: reports
      - store_test_results:
          path: toolkit/build/test-results
